spring:
  application:
    name: isms-api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service
              uri: lb://ISMS-IDENTITY-SERVICE
              predicates:
                - Path=/api/users/**
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins:
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
            add-to-simple-url-handler-mapping: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/isms
server:
  port: 8088
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  application:
    name: ISMS API Gateway
    description: API Gateway for Inventory Management System
    version: 1.0.0
