spring:
  application:
    name: identity-service

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    
server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:yourSecretKeyMustBeAtLeast256BitsLongForHS256AlgorithmToWorkProperly}
  access-token-expiration: 900000      # 15 minutes in milliseconds
  refresh-token-expiration: 604800000  # 7 days in milliseconds