spring:
    application:
        name: identity-service

    datasource:
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:password}
        url: ${DB_URL:jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true}

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

server:
    port: ${SERVER_PORT:8080}